
[general]

	[general.battle]

		[general.battle.lunatic_despair]
			#If the Enchantment is Obtainable
			enabled = true
			#If the Enchantment has any effect
			activated = true
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 2
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "VERY_RARE"
			#If the Enchantment is a Treasure
			treasure = true
			#If the Enchantment is Tradeable by Villagers
			tradeable = false
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 10
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 4
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 40
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Enchantments that are not compatible with this Enchantment
			incompats = []
			#Range: 0.0 ~ 1.7976931348623157E308
			bonus_damage = 0.2

		[general.battle.celestial_blessing]
			#If the Enchantment is Obtainable
			enabled = true
			#If the Enchantment has any effect
			activated = true
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 3
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "UNCOMMON"
			#If the Enchantment is a Treasure
			treasure = false
			#If the Enchantment is Tradeable by Villagers
			tradeable = false
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 14
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 5
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 15
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Enchantments that are not compatible with this Enchantment
			incompats = ["uniquee:climate_tranquility"]
			#Range: 0.0 ~ 1.7976931348623157E308
			speed_bonus_base = 0.08
			#Range: 0.0 ~ 1.7976931348623157E308
			speed_bonus_level = 0.04

		[general.battle.ares_fragment]
			#If the Enchantment is Obtainable
			enabled = true
			#If the Enchantment has any effect
			activated = true
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 4
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "RARE"
			#If the Enchantment is a Treasure
			treasure = true
			#If the Enchantment is Tradeable by Villagers
			tradeable = false
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 25
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 35
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 10
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Enchantments that are not compatible with this Enchantment
			incompats = ["uniquee:berserk", "uniquee:alchemistsgrace", "uniquee:ender_mending", "minecraft:mending"]
			#Range: 0.0 ~ 1.7976931348623157E308
			armor_percentage = 0.6
			#Range: > 0
			base_roll = 10
			#Range: 0.0 ~ 1.7976931348623157E308
			base_roll_multiplier = 1.0
			#Range: 0.0 ~ 1.7976931348623157E308
			durability_reduction_scaling = 1.3
			#Range: > 0
			durability_anti_scaling = 11
			#Range: 0.0 ~ 1.7976931348623157E308
			durability_distribution = 0.6

		[general.battle.ifrits_blessing]
			#If the Enchantment is Obtainable
			enabled = true
			#If the Enchantment has any effect
			activated = true
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 5
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "COMMON"
			#If the Enchantment is a Treasure
			treasure = false
			#If the Enchantment is Tradeable by Villagers
			tradeable = true
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 12
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 2
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 60
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Enchantments that are not compatible with this Enchantment
			incompats = ["uniquee:berserk"]
			#Range: 0.0 ~ 1.7976931348623157E308
			bonus_damage_base = 0.2
			#Range: 0.0 ~ 1.7976931348623157E308
			bonus_damage_level = 0.6

		[general.battle.ifrits_judgement]
			#If the Enchantment is Obtainable
			enabled = true
			#If the Enchantment has any effect
			activated = true
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 2
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "COMMON"
			#If the Enchantment is a Treasure
			treasure = false
			#If the Enchantment is Tradeable by Villagers
			tradeable = false
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 10
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 4
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 40
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Enchantments that are not compatible with this Enchantment
			incompats = []
			#Range: 0.0 ~ 1.7976931348623157E308
			fire_damage_base = 0.4
			#Range: 0.0 ~ 1.7976931348623157E308
			fire_damage_level = 0.1
			#Range: 0.0 ~ 1.7976931348623157E308
			lava_damage_base = 0.4
			#Range: 0.0 ~ 1.7976931348623157E308
			lava_damage_level = 0.1
			#Range: > 0
			burn_duration_base = 30
			#Range: > 0
			burn_duration_level = 10
			#Range: > 0
			lava_hits = 6
			#Range: > 0
			fire_hits = 4

		[general.battle.golem_soul]
			#If the Enchantment is Obtainable
			enabled = true
			#If the Enchantment has any effect
			activated = true
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 4
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "COMMON"
			#If the Enchantment is a Treasure
			treasure = false
			#If the Enchantment is Tradeable by Villagers
			tradeable = true
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 16
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 3
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 50
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Enchantments that are not compatible with this Enchantment
			incompats = []
			#Range: 0.0 ~ 1.7976931348623157E308
			knockback = 0.25
			#Range: 0.0 ~ 1.7976931348623157E308
			speed = 0.05

